services:
  - type: web
    name: guest-registration-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node --max-old-space-size=450 dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
