services:
  - type: web
    name: guest-registration-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
        startOnly: true
      - key: NODE_VERSION
        value: "18"
